# Generated by Django 5.1.2 on 2024-10-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('release_year', models.IntegerField()),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
