# Generated by Django 5.1.2 on 2024-10-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_movie_hints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
    ]
